server:
  port: 2213

spring:
  application:
    name: vault

  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: token
      token: ${VAULT_TOKEN}  # sizning Vault Root Token
      enabled: true
      kv:
        enabled: true
        backend: secret
        default-context: db

  config:
    import: vault://

  datasource:
    url: jdbc:postgresql://localhost:5432/project?currentSchema=vault
    username: ${postgres_username}
    password: ${postgres_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql=true
      dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Spring Boot Actuator config
management:
  endpoint:
    health:
      show-details: always   # health check natijasida barcha detallarni ko‘rsatish
    caches:
      access: none
    metrics:
      access: read_only
    heapdump:
      access: none
    loggers:
      access: none
    threaddump:
      access: none
    beans:
      access: none
    env:
      access: none
    prometheus:
      access: read_only
    info:
      access: read_only
    configprops:
      access: none
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown   # shutdown xavfli, odatda yopiladi

  # Metrics config
  metrics:
    tags:
      application: ${spring.application.name}   # Prometheus/Grafana uchun app tag qo‘shish

  # Health Check config
  health:
    db:
      enabled: true          # DB health check yoqilgan
    diskspace:
      enabled: true          # Disk bo‘sh joyini tekshiradi
    ping:
      enabled: true          # Ping check
    redis:
      enabled: true